SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

GAME_RUNTIME = 0

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
def GET_ASTEROID_MULTIPLIER():
    """Returns the asteroid speed multiplier based on the game runtime."""
    if GAME_RUNTIME / 100 < 1:
        ASTEROID_SPEED_MULTIPLIER = 1
    elif GAME_RUNTIME / 100 < 10:
        ASTEROID_SPEED_MULTIPLIER = 1 * GAME_RUNTIME / 100
    else:
        ASTEROID_SPEED_MULTIPLIER = 10
    return ASTEROID_SPEED_MULTIPLIER

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_SPAWN_IMMUNITY = 1.5  # seconds
PLAYER_SPAWN_IMMUNITY_MAX = 0.5
SHOT_RADIUS = 5

temp = 0